export const checklists = [
    {
        id: 1,
        name: 'Systematic Literature Review',
        description: '',
        checklist: [
            { id: 1, val: '', text: 'Develop a timeline', nestedLevels: 0 },
            { id: 2, val: '', text: 'Identify problem', nestedLevels: 0 },
            { id: 3, val: '', text: 'Identify audience', nestedLevels: 0 },
            { id: 4, val: '', text: 'Identify key terms & phrases', nestedLevels: 0 },
            { id: 5, val: '', text: 'Select literature using key terms & phrases', nestedLevels: 0 },
            { id: 6, val: '', text: 'Code articles', nestedLevels: 0 },
            { id: 7, val: '', text: 'Select articles for review', nestedLevels: 0 },
            { id: 8, val: '', text: 'Identify themes', nestedLevels: 0 },
            { id: 9, val: '', text: 'Write systematic review of literature', nestedLevels: 0 },
            { id: 10, val: '', text: 'Headings', nestedLevels: 1 },
            { id: 11, val: '', text: 'Introduction Section', nestedLevels: 2 },
            { id: 12, val: '', text: 'Methodology Section', nestedLevels: 2 },
            { id: 13, val: '', text: 'Thematic Results Section', nestedLevels: 2 },
            { id: 14, val: '', text: 'Discussion Section', nestedLevels: 2 },
            {
              id: 15,
              val: '',
              text: 'Construct a conceptual or theoretical figure that incorporates the themes',
              nestedLevels: 1,
            },
            {
              id: 16,
              val: '',
              text: 'Use the conceptual or theoretical figure to write your paragraphs to create voice but not just add filler or confusing statements. The paragraphs at this point should be boring and straight to the point',
              nestedLevels: 1,
            },
            {
              id: 17,
              val: '',
              text: 'Edit the literature review (focusing on a creating a consistent and interesting voice with your previously boring and straight to the point paragraphs).',
              nestedLevels: 1,
            },
            { id: 18, val: '', text: 'Reporting out', nestedLevels: 1 },
            { id: 19, val: '', text: 'Send to journal for publication', nestedLevels: 2 },
            { id: 20, val: '', text: 'Use to inform future research', nestedLevels: 2 },
            { id: 21, val: '', text: 'Use as a talking note for future conferences', nestedLevels: 2 },
            {
              id: 22,
              val: '',
              text: 'Use to inform future grants, projects, and research',
              nestedLevels: 2,
            },
            { id: 23, val: '', text: 'Add to CV', nestedLevels: 2 },
          ]
    },
    {
        id: 2,
        name: 'Narrative Literature Review',
        description: '',
        checklist: [
            { id: 1, val: '', text: 'Develop a timeline', nestedLevels: 0 },
            { id: 2, val: '', text: 'Identify problem', nestedLevels: 0 },
            { id: 3, val: '', text: 'Identify themes', nestedLevels: 0 },
            { id: 4, val: '', text: 'Construct a conceptual or theoretical figure that incorporates the themes, nestedLevels: 0' },
            { id: 5, val: '', text: 'Identify audience', nestedLevels: 0 },
            { id: 6, val: '', text: 'Identify key terms & phrases', nestedLevels: 0 },
            { id: 7, val: '', text: 'Select literature using key terms & phrases', nestedLevels: 0 },
            { id: 8, val: '', text: 'Select articles for review based on what supports the themes in your review', nestedLevels: 0 },
            { id: 9, val: '', text: 'Write narrative review of literature', nestedLevels: 0 },
            { id: 10, val: '', text: 'Headings', nestedLevels: 1 },
            { id: 11, val: '', text: 'Introduction Section', nestedLevels: 2 },
            { id: 12, val: '', text: 'Methodology Section', nestedLevels: 2 },
            { id: 13, val: '', text: 'Thematic Results Section', nestedLevels: 2 },
            { id: 14, val: '', text: 'Discussion Section', nestedLevels: 2 },
            {
              id: 15,
              val: '',
              text: 'Use the conceptual or theoretical figure to write your paragraphs to create voice but not just add filler or confusing statements. The paragraphs at this point should be boring and straight to the point',
              nestedLevels: 1,
            },
            {
              id: 16,
              val: '',
              text: 'Edit the literature review (focusing on a creating a consistent and interesting voice with your previously boring and straight to the point paragraphs).',
              nestedLevels: 1,
            },
            { id: 17, val: '', text: 'Reporting out', nestedLevels: 1 },
            { id: 18, val: '', text: 'Send to journal for publication', nestedLevels: 2 },
            { id: 19, val: '', text: 'Use to inform future research', nestedLevels: 2 },
            { id: 20, val: '', text: 'Use as a talking note for future conferences', nestedLevels: 2 },
            {
              id: 21,
              val: '',
              text: 'Use to inform future grants, projects, and research',
              nestedLevels: 2,
            },
            { id: 22, val: '', text: 'Use to go into a dissertation', nestedLevels: 2 },
            { id: 23, val: '', text: 'Add to CV', nestedLevels: 2 },
        ]
    },
    {
        id: 3,
        name: 'Primary Research Article',
        description: '',
        checklist: [
            { id: 1, val: '', text: 'Construct a conceptual, theoretical, or empirical model', nestedLevels: 0 },
            { id: 2, val: '', text: 'Write introduction to model', nestedLevels: 0 },
            { id: 3, val: '', text: 'Define new research questions', nestedLevels: 1 },
            { id: 4, val: '', text: 'Write methodology', nestedLevels: 0 },
            { id: 5, val: '', text: 'Describe sample and/or participants', nestedLevels: 1 },
            { id: 6, val: '', text: 'Describe instruments', nestedLevels: 1 },
            { id: 7, val: '', text: 'Describe measures', nestedLevels: 1 },
            { id: 8, val: '', text: 'Describe new analytic method', nestedLevels: 1 },
            { id: 9, val: '', text: 'Write results', nestedLevels: 0 },
            { id: 10, val: '', text: 'Each results sections needs to link to a research question', nestedLevels: 1 },
            { id: 11, val: '', text: 'Create tables and figures in this section', nestedLevels: 1 },
            { id: 12, val: '', text: 'Write discussion', nestedLevels: 0 },
            { id: 13, val: '', text: 'Restate overarching problem and research questions', nestedLevels: 1 },
            { id: 14, val: '', text: 'Connect results to individual research questions', nestedLevels: 1 },
            { id: 15, val: '', text: 'Describing 3-7 strengths related to methods or results', nestedLevels: 1 },
            { id: 16, val: '', text: 'Describing 3-7 limitations related to methods or results', nestedLevels: 1 },
            { id: 17, val: '', text: 'Describing 3-7 applications related to results', nestedLevels: 1 },
            { id: 18, val: '', text: 'Describing 3-7 theoretical implications related to results', nestedLevels: 1 },
            { id: 19, val: '', text: 'Identify supporting institutions and individuals', nestedLevels: 1 },
            { id: 20, val: '', text: 'Reporting out', nestedLevels: 1 },
            { id: 21, val: '', text: 'Send to journal for publication', nestedLevels: 2 },
            { id: 22, val: '', text: 'Use to inform future research', nestedLevels: 2 },
            { id: 23, val: '', text: 'Use as a talking note for future conferences', nestedLevels: 2 },
            {
              id: 24,
              val: '',
              text: 'Use to inform future grants, projects, and research',
              nestedLevels: 2,
            },
            { id: 25, val: '', text: 'Use to go into a dissertation', nestedLevels: 2 },
            { id: 26, val: '', text: 'Add to CV', nestedLevels: 2 },
        ]
    },
    {
        id: 4,
        name: 'Secondary Research Article',
        description: '',
        checklist: [
            { id: 1, val: '', text: 'Construct a conceptual, theoretical, or empirical model', nestedLevels: 0 },
            { id: 2, val: '', text: 'Write introduction to model', nestedLevels: 0 },
            { id: 3, val: '', text: 'Define new research questions', nestedLevels: 1 },
            { id: 4, val: '', text: 'Write methodology', nestedLevels: 0 },
            { id: 5, val: '', text: 'Describe sample and/or participants', nestedLevels: 1 },
            { id: 6, val: '', text: 'Describe instruments', nestedLevels: 1 },
            { id: 7, val: '', text: 'Describe measures', nestedLevels: 1 },
            { id: 8, val: '', text: 'Describe new analytic method', nestedLevels: 1 },
            { id: 9, val: '', text: 'Write results', nestedLevels: 0 },
            { id: 10, val: '', text: 'Each results sections needs to link to a research question', nestedLevels: 1 },
            { id: 11, val: '', text: 'Create tables and figures in this section', nestedLevels: 1 },
            { id: 12, val: '', text: 'Write discussion', nestedLevels: 0 },
            { id: 13, val: '', text: 'Restate overarching problem and research questions', nestedLevels: 1 },
            { id: 14, val: '', text: 'Connect results to individual research questions', nestedLevels: 1 },
            { id: 15, val: '', text: 'Describing 3-7 strengths related to methods or results', nestedLevels: 1 },
            { id: 16, val: '', text: 'Describing 3-7 limitations related to methods or results', nestedLevels: 1 },
            { id: 17, val: '', text: 'Describing 3-7 applications related to results', nestedLevels: 1 },
            { id: 18, val: '', text: 'Describing 3-7 theoretical implications related to results', nestedLevels: 1 },
            { id: 19, val: '', text: 'Identify supporting institutions and individuals', nestedLevels: 1 },
            { id: 20, val: '', text: 'Reporting out', nestedLevels: 1 },
            { id: 21, val: '', text: 'Send to journal for publication', nestedLevels: 2 },
            { id: 22, val: '', text: 'Use to inform future research', nestedLevels: 2 },
            { id: 23, val: '', text: 'Use as a talking note for future conferences', nestedLevels: 2 },
            {
              id: 24,
              val: '',
              text: 'Use to inform future grants, projects, and research',
              nestedLevels: 2,
            },
            { id: 25, val: '', text: 'Use to go into a dissertation', nestedLevels: 2 },
            { id: 26, val: '', text: 'Add to CV', nestedLevels: 2 },
        ]
    },
    {
        id: 5,
        name: 'Meta Research Article',
        description: '',
        checklist: [
            { id: 1, val: '', text: 'Construct a conceptual, theoretical, or empirical model', nestedLevels: 0 },
            { id: 2, val: '', text: 'Write introduction to model', nestedLevels: 0 },
            { id: 3, val: '', text: 'Define new research questions', nestedLevels: 1 },
            { id: 4, val: '', text: 'Identify body of literature', nestedLevels: 1 },
            { id: 5, val: '', text: 'Write methodology', nestedLevels: 0 },
            { id: 6, val: '', text: 'Describe articles', nestedLevels: 1 },
            { id: 7, val: '', text: 'Describe participants across articles', nestedLevels: 1 },
            { id: 8, val: '', text: 'Describe instruments across articles', nestedLevels: 1 },
            { id: 9, val: '', text: 'Describe measures across articles', nestedLevels: 1 },
            { id: 10, val: '', text: 'Standardize results across articles', nestedLevels: 1 },
            { id: 11, val: '', text: 'Write results', nestedLevels: 0 },
            { id: 12, val: '', text: 'Each results sections needs to link to a research question', nestedLevels: 1 },
            { id: 13, val: '', text: 'Create tables and figures in this section', nestedLevels: 1 },
            { id: 14, val: '', text: 'Describe publication bias', nestedLevels: 1 },
            { id: 15, val: '', text: 'Write discussion', nestedLevels: 0 },
            { id: 16, val: '', text: 'Restate overarching problem and research questions', nestedLevels: 1 },
            { id: 17, val: '', text: 'Connect results to individual research questions', nestedLevels: 1 },
            { id: 18, val: '', text: 'Describing 3-7 strengths related to methods or results', nestedLevels: 1 },
            { id: 19, val: '', text: 'Describing 3-7 limitations related to methods or results', nestedLevels: 1 },
            { id: 20, val: '', text: 'Describing 3-7 applications related to results', nestedLevels: 1 },
            { id: 21, val: '', text: 'Describing 3-7 theoretical implications related to results', nestedLevels: 1 },
            { id: 22, val: '', text: 'Identify supporting institutions and individuals', nestedLevels: 1 },
            { id: 23, val: '', text: 'Reporting out', nestedLevels: 1 },
            { id: 24, val: '', text: 'Send to journal for publication', nestedLevels: 2 },
            { id: 25, val: '', text: 'Use to inform future research', nestedLevels: 2 },
            { id: 26, val: '', text: 'Use as a talking note for future conferences', nestedLevels: 2 },
            {
              id: 27,
              val: '',
              text: 'Use to inform future grants, projects, and research',
              nestedLevels: 2,
            },
            { id: 28, val: '', text: 'Use to go into a dissertation', nestedLevels: 2 },
            { id: 29, val: '', text: 'Add to CV', nestedLevels: 2 },
        ]
    },
    {
        id: 6,
        name: 'Journal Op Ed',
        description: '',
        checklist: [
            { id: 1, val: '', text: 'Identify problem', nestedLevels: 0 },
            { id: 2, val: '', text: 'Identify 3-7 positions in relation to the problem', nestedLevels: 0 },
            { id: 3, val: '', text: 'Identify 3-7 researchers in those positions', nestedLevels: 0 },
            { id: 4, val: '', text: 'Construct a model showing how the positions relate to one another', nestedLevels: 0 },
            { id: 5, val: '', text: 'Write Op Ed', nestedLevels: 0 },
            { id: 6, val: '', text: 'Write to the model with the info from the 3-7 researchers', nestedLevels: 1 },
            { id: 7, val: '', text: 'There should be a section for each position', nestedLevels: 2 },
            { id: 8, val: '', text: 'Write your position as to the validity or invalidity of each of these positions showing the pros and the cons', nestedLevels: 2 },
            { id: 9, val: '', text: 'Reporting out', nestedLevels: 0 },
            { id: 10, val: '', text: 'Publish to an journal associated with your professional society', nestedLevels: 1 },
        ]
    },
    {
        id: 7,
        name: 'Periodical Op Ed (Newspaper/Magazine)',
        description: '',
        checklist: [
            { id: 1, val: '', text: 'Identify problem', nestedLevels: 0 },
            { id: 2, val: '', text: 'Identify 1 positions in relation to the problem', nestedLevels: 0 },
            { id: 3, val: '', text: 'Identify 3-7 researchers in that position', nestedLevels: 0 },
            { id: 4, val: '', text: 'Construct a model showing how the positions relate to one another', nestedLevels: 0 },
            { id: 5, val: '', text: 'Write Op Ed', nestedLevels: 0 },
            { id: 6, val: '', text: 'Write a section to the model with the info from the 3-7 researchers', nestedLevels: 1 },
            { id: 7, val: '', text: 'Write your position as to the validity or invalidity of the position showing only the pros or only the cons. Take a position.', nestedLevels: 2 },
            { id: 8, val: '', text: 'Edit the writing to ensure a consistent voice', nestedLevels: 2 },
            { id: 9, val: '', text: 'Reporting out', nestedLevels: 0 },
            { id: 10, val: '', text: 'Publish to an journal associated with your professional society', nestedLevels: 1 },
            { id: 11, val: '', text: 'Add to CV', nestedLevels: 1 },
        ]
    },
    {
        id: 8,
        name: 'Conference Paper',
        description: '',
        checklist: [
            { id: 1, val: '', text: 'Identify conference', nestedLevels: 0 },
            { id: 2, val: '', text: 'Register for conference', nestedLevels: 0 },
            { id: 3, val: '', text: 'Identify the type of paper you want to present (Review of literature, theoretical, methodological)', nestedLevels: 0 },
            { id: 4, val: '', text: 'Write a 250-350 word abstract to include with your application to present', nestedLevels: 0 },
            { id: 5, val: '', text: 'Send application to present in the conference and wait for a response', nestedLevels: 0 },
            { id: 6, val: '', text: 'Determine if you want to publish in conference proceedings or a journal', nestedLevels: 0 },
            { id: 7, val: '', text: '', nestedLevels: 0 },
            { id: 8, val: '', text: 'Create presentation', nestedLevels: 0 },
            { id: 9, val: '', text: 'Slides should correspond to major headings in the article', nestedLevels: 1 },
            { id: 10, val: '', text: 'Focus on figures over tables', nestedLevels: 1 },
            { id: 11, val: '', text: 'No more than 3-7 words per line', nestedLevels: 1 },
            { id: 12, val: '', text: 'No more than 3-7 lines per slide', nestedLevels: 1 },
            { id: 13, val: '', text: 'Include a recognition slide at the end (collaborators, supporters of research, anyone who helped write or edit it, and thank the conference individuals)', nestedLevels: 1 },
            { id: 14, val: '', text: 'Go to the conference and present!', nestedLevels: 0 },
            { id: 15, val: '', text: 'Add to CV', nestedLevels: 0 },
        ]
    },
    {
        id: 9,
        name: 'Chapter Dissertation',
        description: '',
        checklist: [
            { id: 1, val: '', text: 'Determine your research interest', nestedLevels: 0 },
            { id: 2, val: '', text: 'Identify potential advisors', nestedLevels: 0 },
            { id: 3, val: '', text: 'Communicate with the potential advisor', nestedLevels: 1 },
            { id: 4, val: '', text: 'Select advisor', nestedLevels: 1 },
            { id: 5, val: '', text: 'Apply to graduate program with the selected advisor', nestedLevels: 0 },
            { id: 6, val: '', text: 'Begin coursework', nestedLevels: 0 },
            { id: 7, val: '', text: 'Begin research projects', nestedLevels: 0 },
            { id: 8, val: '', text: 'Identify committee members', nestedLevels: 0 },
            { id: 9, val: '', text: 'Identify 3-7 important articles that will influence your dissertation', nestedLevels: 0 },
            { id: 10, val: '', text: 'Identify overarching statement', nestedLevels: 0 },
            { id: 11, val: '', text: 'Identify research questions', nestedLevels: 0 },
            { id: 12, val: '', text: 'Communicate with advisor', nestedLevels: 0 },
            { id: 13, val: '', text: 'Construct conceptual model', nestedLevels: 0 },
            { id: 14, val: '', text: 'Use the conceptual model to write a 5-10 page synopsis (proposal) of the dissertation', nestedLevels: 0 },
            { id: 15, val: '', text: 'Include research questions in this synopsis', nestedLevels: 1 },
            { id: 16, val: '', text: 'Communicate with advisor', nestedLevels: 0 },
            { id: 17, val: '', text: 'Propose synopsis to committee', nestedLevels: 0 },
            { id: 18, val: '', text: 'Conduct research', nestedLevels: 0 },
            { id: 19, val: '', text: 'Communicate with advisor consistently', nestedLevels: 1 },
            { id: 20, val: '', text: 'Chapters', nestedLevels: 0 },
            { id: 21, val: '', text: 'Chapter 1 (Introduction)', nestedLevels: 1 },
            { id: 22, val: '', text: 'Write overreaching statement', nestedLevels: 2 },
            { id: 23, val: '', text: 'Communicate with advisor', nestedLevels: 2},
            { id: 24, val: '', text: 'Introduce the conceptual model', nestedLevels:2 },
            { id: 25, val: '', text: 'Communicate with advisor', nestedLevels: 2},
            { id: 26, val: '', text: 'Write to your research questions', nestedLevels: 2 },
            { id: 27, val: '', text: 'Communicate with advisor', nestedLevels: 2 },
            { id: 28, val: '', text: 'Chapter 2 (Literature)', nestedLevels: 1 },
            { id: 29, val: '', text: 'Follow the steps above for writing a narrative review of literature', nestedLevels: 2 },
            { id: 30, val: '', text: 'Communicate with advisor consistently', nestedLevels: 3 },
            { id: 31, val: '', text: 'Chapter 3 (Methodology)', nestedLevels: 1 },
            { id: 32, val: '', text: 'Describe sample and/or participants', nestedLevels: 2 },
            { id: 33, val: '', text: 'Communicate with advisor', nestedLevels: 3 },
            { id: 34, val: '', text: 'Describe instruments', nestedLevels: 2 },
            { id: 35, val: '', text: 'Communicate with advisor', nestedLevels: 3 },
            { id: 36, val: '', text: 'Describe measures', nestedLevels: 2 },
            { id: 37, val: '', text: 'Communicate with advisor', nestedLevels: 3 },
            { id: 38, val: '', text: 'Chapter 4 (Results)', nestedLevels: 1 },
            { id: 39, val: '', text: 'Each results section needs to link to a research question', nestedLevels: 2 },
            { id: 40, val: '', text: 'Communicate with advisor', nestedLevels: 3 },
            { id: 41, val: '', text: 'Create tables and figures in this chapter', nestedLevels: 2 },
            { id: 42, val: '', text: 'Communicate with advisor**', nestedLevels: 3 },
            { id: 43, val: '', text: 'Chapter 5 (Discussion)', nestedLevels: 1 },
            { id: 44, val: '', text: 'Identify supporting institutions and individuals', nestedLevels: 2 },
            { id: 45, val: '', text: 'Communicate with advisor', nestedLevels: 3 },
            { id: 46, val: '', text: 'Restate overarching problem and research questions', nestedLevels: 2 },
            { id: 47, val: '', text: 'Communicate with advisor', nestedLevels: 3 },
            { id: 48, val: '', text: 'Connect results to individual research questions', nestedLevels: 2 },
            { id: 49, val: '', text: 'Communicate with advisor', nestedLevels: 3 },
            { id: 50, val: '', text: 'Describing 3-7 strengths related to methods or results', nestedLevels: 2 },
            { id: 51, val: '', text: 'Communicate with advisor', nestedLevels: 3 },
            { id: 52, val: '', text: 'Describing 3-7 limitations related to methods or results', nestedLevels: 2 },
            { id: 53, val: '', text: 'Communicate with advisor', nestedLevels: 3 },
            { id: 54, val: '', text: 'Describing 3-7 applications related to results', nestedLevels: 2 },
            { id: 55, val: '', text: 'Communicate with advisor', nestedLevels: 3 },
            { id: 56, val: '', text: 'Describing 3-7 theoretical implications related to results', nestedLevels: 2 },
            { id: 57, val: '', text: 'Communicate with advisor', nestedLevels: 3 },
            { id: 58, val: '', text: 'Present dissertation to committee in the defense', nestedLevels: 0 },
            { id: 59, val: '', text: 'Complete edits from committee members', nestedLevels: 0 },
            { id: 60, val: '', text: 'Communicate with advisor**', nestedLevels: 1 },
            { id: 61, val: '', text: 'Submit to university', nestedLevels: 0 },
            { id: 62, val: '', text: 'Complete edits from university', nestedLevels: 0 },
            { id: 63, val: '', text: 'Communicate with advisor', nestedLevels: 1 },
            { id: 64, val: '', text: 'Submit final dissertation to university', nestedLevels: 0 },
        ]
    },
    {
        id: 10,
        name: 'Article Dissertation',
        description: '',
        checklist: [
            { id: 1, val: '', text: 'Determine your research interest', nestedLevels: 0 },
            { id: 2, val: '', text: 'Identify potential advisors', nestedLevels: 0 },
            { id: 3, val: '', text: 'Communicate with the potential advisor', nestedLevels: 1 },
            { id: 4, val: '', text: 'Select advisor', nestedLevels: 1 },
            { id: 5, val: '', text: 'Apply to graduate program with the selected advisor', nestedLevels: 0 },
            { id: 6, val: '', text: 'Begin coursework', nestedLevels: 0 },
            { id: 7, val: '', text: 'Begin research projects', nestedLevels: 0 },
            { id: 8, val: '', text: 'Identify committee members', nestedLevels: 0 },
            { id: 9, val: '', text: 'Identify 3-7 important articles that will influence your dissertation', nestedLevels: 0 },
            { id: 10, val: '', text: 'Identify overarching statement', nestedLevels: 0 },
            { id: 11, val: '', text: 'Identify research questions', nestedLevels: 0 },
            { id: 12, val: '', text: 'Communicate with advisor', nestedLevels: 0 },
            { id: 13, val: '', text: 'Construct conceptual model', nestedLevels: 0 },
            { id: 14, val: '', text: 'Communicate with advisor', nestedLevels: 0 },
            { id: 15, val: '', text: 'Write Chapter 1', nestedLevels: 0 },
            { id: 16, val: '', text: 'Combine overarching research statement, conceptual model, and research questions', nestedLevels: 1 },
            { id: 17, val: '', text: 'Communicate with advisor', nestedLevels: 1 },
            { id: 18, val: '', text: 'Determine if you are going to write a systematic or narrative review article', nestedLevels: 0 },
            { id: 19, val: '', text: 'Communicate with advisor', nestedLevels: 1 },
            { id: 20, val: '', text: 'Systematic', nestedLevels: 1 },
            { id: 21, val: '', text: 'Follow checklist for systematic literature review', nestedLevels: 2 },
            { id: 22, val: '', text: 'Communicate with advisor', nestedLevels: 2 },
            { id: 23, val: '', text: 'Narrative', nestedLevels: 1 },
            { id: 24, val: '', text: 'Follow checklist for narrative literature review', nestedLevels: 2 },
            { id: 25, val: '', text: 'Communicate with advisor', nestedLevels: 2 },
            { id: 26, val: '', text: 'Construct a 3-5 page synopsis of your methodology', nestedLevels: 0 },
            { id: 27, val: '', text: 'Combine Chapter 1 with review article and 3-5 page synopsis of methodology for proposal to the committee', nestedLevels: 0 },
            { id: 28, val: '', text: 'Communicate with advisor', nestedLevels: 0 },
            { id: 29, val: '', text: 'Propose research agenda to committee', nestedLevels: 0 },
            { id: 30, val: '', text: 'Conduct research', nestedLevels: 0 },
            { id: 31, val: '', text: 'Communicate with advisor consistently', nestedLevels: 1 },
            { id: 32, val: '', text: 'Chapters', nestedLevels: 0 },
            { id: 33, val: '', text: 'Chapter 1 (Introduction)', nestedLevels: 1 },
            { id: 34, val: '', text: 'This is already written from steps taken above', nestedLevels: 2 },
            { id: 35, val: '', text: 'Chapter 2 (Literature)', nestedLevels: 1 },
            { id: 36, val: '', text: 'This is already written from steps taken above', nestedLevels: 2 },
            { id: 37, val: '', text: 'Chapter 3 (Methodological Article)', nestedLevels: 1 },
            { id: 38, val: '', text: 'Construct a narrative review of literature from sections of chapter 2', nestedLevels: 2 },
            { id: 39, val: '', text: 'Follow steps above for narrative literature review', nestedLevels: 2 },
            { id: 40, val: '', text: 'Communicate with advisor', nestedLevels: 2 },
            { id: 41, val: '', text: 'Construct sections of article', nestedLevels: 2 },
            { id: 42, val: '', text: 'Introduction', nestedLevels: 3 },
            { id: 43, val: '', text: 'Methods', nestedLevels: 3 },
            { id: 44, val: '', text: 'Results', nestedLevels: 3 },
            { id: 45, val: '', text: 'Discussion', nestedLevels: 3 },
            { id: 46, val: '', text: 'Communicate with advisor', nestedLevels: 2 },
            { id: 47, val: '', text: 'Chapter 4 (Theoretical Article)', nestedLevels: 1 },
            { id: 48, val: '', text: 'Construct a narrative review of literature from sections of chapter 2', nestedLevels: 2 },
            { id: 49, val: '', text: 'Communicate with advisor', nestedLevels: 2 },
            { id: 50, val: '', text: 'Construct sections of article', nestedLevels: 2 },
            { id: 51, val: '', text: 'Introduction', nestedLevels: 3 },
            { id: 52, val: '', text: 'Methods', nestedLevels: 3 },
            { id: 53, val: '', text: 'Results', nestedLevels: 3 },
            { id: 54, val: '', text: 'Discussion', nestedLevels: 3 },
            { id: 55, val: '', text: 'Communicate with advisor', nestedLevels: 3 },
            { id: 56, val: '', text: 'Chapter 5 (Synthesis)', nestedLevels: 1 },
            { id: 57, val: '', text: 'Identify supporting institutions and individuals', nestedLevels: 2 },
            { id: 58, val: '', text: 'Communicate with advisor', nestedLevels: 3 },
            { id: 59, val: '', text: 'Restate overarching problem and research questions', nestedLevels: 2 },
            { id: 60, val: '', text: 'Communicate with advisor', nestedLevels: 3 },
            { id: 61, val: '', text: 'Connect results to individual research questions', nestedLevels: 2 },
            { id: 62, val: '', text: 'Communicate with advisor', nestedLevels: 3 },
            { id: 63, val: '', text: 'Describing 3-7 strengths related to methods or results', nestedLevels: 2 },
            { id: 64, val: '', text: 'Communicate with advisor', nestedLevels: 3 },
            { id: 65, val: '', text: 'Describing 3-7 limitations related to methods or results', nestedLevels: 2 },
            { id: 66, val: '', text: 'Communicate with advisor', nestedLevels: 3 },
            { id: 67, val: '', text: 'Describing 3-7 applications related to results', nestedLevels: 2 },
            { id: 68, val: '', text: 'Communicate with advisor', nestedLevels: 3 },
            { id: 69, val: '', text: 'Describing 3-7 theoretical implications related to results', nestedLevels: 2 },
            { id: 70, val: '', text: 'Communicate with advisor', nestedLevels: 3 },
            { id: 71, val: '', text: 'Present dissertation to committee in the defense', nestedLevels: 0 },
            { id: 72, val: '', text: 'Complete edits from committee members', nestedLevels: 0 },
            { id: 73, val: '', text: 'Communicate with advisor', nestedLevels: 1 },
            { id: 74, val: '', text: 'Submit to university', nestedLevels: 0 },
            { id: 75, val: '', text: 'Complete edits from university', nestedLevels: 0 },
            { id: 76, val: '', text: 'Communicate with advisor', nestedLevels: 1 },
            { id: 77, val: '', text: 'Submit final dissertation to university', nestedLevels: 0 },
        ]
    },
    {
        id: 11,
        name: 'Book Chapter',
        description: '',
        checklist: [
            { id: 1, val: '', text: 'Identify editor through university or publishing company', nestedLevels: 0 },
            { id: 2, val: '', text: 'Contact editor', nestedLevels: 0 },
            { id: 3, val: '', text: 'Submit 3-5 page synopsis of the book chapter you want to write', nestedLevels: 0 },
            { id: 4, val: '', text: 'Create conceptual model', nestedLevels: 0 },
            { id: 5, val: '', text: 'Write to conceptual model', nestedLevels: 0 },
            { id: 6, val: '', text: 'Identify and create visuals', nestedLevels: 0 },
            { id: 7, val: '', text: 'Submit to editor', nestedLevels: 0 },
            { id: 8, val: '', text: 'Make edits', nestedLevels: 0 },
        ]
    },
    {
        id: 12,
        name: 'Book',
        description: '',
        checklist: [
            { id: 1, val: '', text: 'Identify story you want to tell or textbook content you want to write about', nestedLevels: 0 },
            { id: 2, val: '', text: 'Identify agent', nestedLevels: 0 },
            { id: 3, val: '', text: 'Contact agent', nestedLevels: 1 },
            { id: 4, val: '', text: 'Identify publishing company', nestedLevels: 0 },
            { id: 5, val: '', text: 'Contact publishing company', nestedLevels: 1 },
            { id: 6, val: '', text: 'Construct conceptual model for the purpose of the book', nestedLevels: 0 },
            { id: 7, val: '', text: 'Write 5-10 page synopsis', nestedLevels: 0 },
            { id: 8, val: '', text: 'Send to agent for review', nestedLevels: 0 },
            { id: 9, val: '', text: 'Submit to publishing company', nestedLevels: 0 },
            { id: 10, val: '', text: 'Begin work on book for publishing company, or if self-publishing, skip agent and publisher steps above', nestedLevels: 0 },
            { id: 11, val: '', text: 'Decide on type of book', nestedLevels: 0 },
            { id: 12, val: '', text: `Text (About everyone else's idea)`, nestedLevels: 1 },
            { id: 13, val: '', text: 'Identify 3-7 major themes (these can become sections of chapters, or chapters themselves depending on the size of the book)', nestedLevels: 2 },
            { id: 14, val: '', text: 'Construct literature database for each theme', nestedLevels: 2 },
            { id: 15, val: '', text: 'Write chapters for each theme, or 3-7 chapters under each section which represents a major theme', nestedLevels: 2 },
            { id: 16, val: '', text: 'Create and integrate visuals', nestedLevels: 2 },
            { id: 17, val: '', text: 'Submit to publisher or self-publish', nestedLevels: 2 },
            { id: 18, val: '', text: 'If using a publisher, make edits/revise, and resubmit', nestedLevels: 3 },
            { id: 19, val: '', text: 'Narrative (About your idea)', nestedLevels: 1 },
            { id: 20, val: '', text: 'Identify story you want to tell', nestedLevels: 2 },
            { id: 21, val: '', text: 'Identify 3-7 major themes supporting the narrative (these can become sections of chapters, or chapters themselves depending on the size of the book)', nestedLevels: 2 },
            { id: 22, val: '', text: 'Write chapters for each theme, or 3-7 chapters under each section which represents a major theme', nestedLevels: 2 },
            { id: 23, val: '', text: 'Create and integrate visuals if needed', nestedLevels: 2 },
            { id: 24, val: '', text: 'Submit to publisher or self-publish', nestedLevels: 2 },
            { id: 25, val: '', text: 'If using a publisher, make edits/revise, and resubmit', nestedLevels: 3 },
        ]
    },
    {
        id: 13,
        name: 'Book Series',
        description: '',
        checklist: [
            { id: 1, val: '', text: 'Follow steps for text book above, but instead of individual themes being a chapter, make them an entire book.', nestedLevels: 0 },
        ]
    },
    {
        id: 14,
        name: 'National Grant',
        description: '',
        checklist: [
            { id: 1, val: '', text: 'Identification', nestedLevels: 0 },
            { id: 2, val: '', text: 'Identify agency', nestedLevels: 1 },
            { id: 3, val: '', text: 'Identify division ( Identify segment within your field that the national agency supports )', nestedLevels: 1 },
            { id: 4, val: '', text: 'Identify contact person at agency', nestedLevels: 1 },
            { id: 5, val: '', text: 'Identify key terms', nestedLevels: 1 },
            { id: 6, val: '', text: 'Conduct initial search for grants', nestedLevels: 1 },
            { id: 7, val: '', text: 'Code grants for viability (Are we eligible)', nestedLevels: 1 },
            { id: 8, val: '', text: 'Identify important dates', nestedLevels: 1 },
            { id: 9, val: '', text: 'Select a grant(s)', nestedLevels: 1 },
            { id: 10, val: '', text: 'Writing', nestedLevels: 0 },
            { id: 11, val: '', text: 'Review grant', nestedLevels: 1 },
            { id: 12, val: '', text: 'Create research questions', nestedLevels: 1 },
            { id: 13, val: '', text: 'Construct a review of literature (follow steps above)', nestedLevels: 1 },
            { id: 14, val: '', text: 'Construct narratives for sections within grant', nestedLevels: 1 },
            { id: 15, val: '', text: 'Submission', nestedLevels: 0 },
            { id: 16, val: '', text: 'Identify and contact grant contact person', nestedLevels: 1 },
            { id: 17, val: '', text: 'Plan to submit 3-7 days before deadline', nestedLevels: 1 },
            { id: 18, val: '', text: 'Submit', nestedLevels: 1 },
            { id: 19, val: '', text: 'Reach out to contact person to make sure everything is good', nestedLevels: 1 },
        ]
    },
    {
        id: 15,
        name: 'State Grant',
        description: '',
        checklist: [
            { id: 1, val: '', text: 'Identification', nestedLevels: 0 },
            { id: 2, val: '', text: 'Identify agency', nestedLevels: 1 },
            { id: 3, val: '', text: 'Identify division ( Identify segment within your field that the state agency supports )', nestedLevels: 1 },
            { id: 4, val: '', text: 'Identify contact person at agency', nestedLevels: 1 },
            { id: 5, val: '', text: 'Identify key terms', nestedLevels: 1 },
            { id: 6, val: '', text: 'Conduct initial search for grants', nestedLevels: 1 },
            { id: 7, val: '', text: 'Code grants for viability (Are we eligible)', nestedLevels: 1 },
            { id: 8, val: '', text: 'Identify important dates', nestedLevels: 1 },
            { id: 9, val: '', text: 'Select a grant(s)', nestedLevels: 1 },
            { id: 10, val: '', text: 'Writing', nestedLevels: 0 },
            { id: 11, val: '', text: 'Review grant', nestedLevels: 1 },
            { id: 12, val: '', text: 'Create research questions', nestedLevels: 1 },
            { id: 13, val: '', text: 'Construct a review of literature (follow steps above)', nestedLevels: 1 },
            { id: 14, val: '', text: 'Construct narratives for sections within grant', nestedLevels: 1 },
            { id: 15, val: '', text: 'Submission', nestedLevels: 0 },
            { id: 16, val: '', text: 'Identify and contact grant contact person', nestedLevels: 1 },
            { id: 17, val: '', text: 'Plan to submit 3-7 days before deadline', nestedLevels: 1 },
            { id: 18, val: '', text: 'Submit', nestedLevels: 1 },
            { id: 19, val: '', text: 'Reach out to contact person to make sure everything is good', nestedLevels: 1 },
        ]
    },
    {
        id: 16,
        name: 'Local Grant',
        description: '',
        checklist: [
            { id: 1, val: '', text: 'Identification', nestedLevels: 0 },
            { id: 2, val: '', text: 'Identify agency', nestedLevels: 1 },
            { id: 3, val: '', text: 'Identify division ( Identify segment within your field that the local agency supports )', nestedLevels: 1 },
            { id: 4, val: '', text: 'Identify contact person at agency', nestedLevels: 1 },
            { id: 5, val: '', text: 'Identify key terms', nestedLevels: 1 },
            { id: 6, val: '', text: 'Conduct initial search for grants', nestedLevels: 1 },
            { id: 7, val: '', text: 'Code grants for viability (Are we eligible)', nestedLevels: 1 },
            { id: 8, val: '', text: 'Identify important dates', nestedLevels: 1 },
            { id: 9, val: '', text: 'Select a grant(s)', nestedLevels: 1 },
            { id: 10, val: '', text: 'Writing', nestedLevels: 0 },
            { id: 11, val: '', text: 'Review grant', nestedLevels: 1 },
            { id: 12, val: '', text: 'Create research questions', nestedLevels: 1 },
            { id: 13, val: '', text: 'Construct a review of literature (follow steps above)', nestedLevels: 1 },
            { id: 14, val: '', text: 'Construct narratives for sections within grant', nestedLevels: 1 },
            { id: 15, val: '', text: 'Submission', nestedLevels: 0 },
            { id: 16, val: '', text: 'Identify and contact grant contact person', nestedLevels: 1 },
            { id: 17, val: '', text: 'Plan to submit 3-7 days before deadline', nestedLevels: 1 },
            { id: 18, val: '', text: 'Submit', nestedLevels: 1 },
            { id: 19, val: '', text: 'Reach out to contact person to make sure everything is good', nestedLevels: 1 },
        ]
    },
    {
        id: 17,
        name: 'Institutional Grant',
        description: '',
        checklist: [
            { id: 1, val: '', text: 'Identification', nestedLevels: 0 },
            { id: 2, val: '', text: 'Identify contact person at institution', nestedLevels: 1 },
            { id: 3, val: '', text: 'Identify key terms', nestedLevels: 1 },
            { id: 4, val: '', text: 'Identify important dates', nestedLevels: 1 },
            { id: 5, val: '', text: 'Writing', nestedLevels: 0 },
            { id: 6, val: '', text: 'Review grant', nestedLevels: 1 },
            { id: 7, val: '', text: 'Create research questions', nestedLevels: 1 },
            { id: 8, val: '', text: 'Construct a review of literature (follow steps above)', nestedLevels: 1 },
            { id: 9, val: '', text: 'Construct narratives for sections within grant', nestedLevels: 1 },
            { id: 10, val: '', text: 'Submission', nestedLevels: 0 },
            { id: 11, val: '', text: 'Identify and contact grant contact person', nestedLevels: 1 },
            { id: 12, val: '', text: 'Plan to submit 3-7 days before deadline', nestedLevels: 1 },
            { id: 13, val: '', text: 'Submit', nestedLevels: 1 },
            { id: 14, val: '', text: 'Reach out to contact person to make sure everything is good', nestedLevels: 1 },
        ]
    },
    {
        id: 18,
        name: 'Private Grant',
        description: '',
        checklist: [
            { id: 1, val: '', text: 'Identification', nestedLevels: 0 },
            { id: 2, val: '', text: 'Identify agency', nestedLevels: 1 },
            { id: 3, val: '', text: 'Identify division ( Identify segment within your field that the private organization supports )', nestedLevels: 1 },
            { id: 4, val: '', text: 'Identify contact person at agency', nestedLevels: 1 },
            { id: 5, val: '', text: 'Identify key terms', nestedLevels: 1 },
            { id: 6, val: '', text: 'Conduct initial search for grants', nestedLevels: 1 },
            { id: 7, val: '', text: 'Code grants for viability (Are we eligible)', nestedLevels: 1 },
            { id: 8, val: '', text: 'Identify important dates', nestedLevels: 1 },
            { id: 9, val: '', text: 'Select a grant(s)', nestedLevels: 1 },
            { id: 10, val: '', text: 'Writing', nestedLevels: 0 },
            { id: 11, val: '', text: 'Review grant', nestedLevels: 1 },
            { id: 12, val: '', text: 'Create research questions', nestedLevels: 1 },
            { id: 13, val: '', text: 'Construct a review of literature (follow steps above)', nestedLevels: 1 },
            { id: 14, val: '', text: 'Construct narratives for sections within grant', nestedLevels: 1 },
            { id: 15, val: '', text: 'Submission', nestedLevels: 0 },
            { id: 16, val: '', text: 'Identify and contact grant contact person', nestedLevels: 1 },
            { id: 17, val: '', text: 'Plan to submit 3-7 days before deadline', nestedLevels: 1 },
            { id: 18, val: '', text: 'Submit', nestedLevels: 1 },
            { id: 19, val: '', text: 'Reach out to contact person to make sure everything is good', nestedLevels: 1 },
        ]
    },
    {
        id: 19,
        name: 'Corporation/Professional Grant',
        description: '',
        checklist: [
            { id: 1, val: '', text: 'Identification', nestedLevels: 0 },
            { id: 2, val: '', text: 'Identify agency', nestedLevels: 1 },
            { id: 3, val: '', text: 'Identify division ( Identify segment within your field that the company supports )', nestedLevels: 1 },
            { id: 4, val: '', text: 'Identify contact person at agency', nestedLevels: 1 },
            { id: 5, val: '', text: 'Identify key terms', nestedLevels: 1 },
            { id: 6, val: '', text: 'Conduct initial search for grants', nestedLevels: 1 },
            { id: 7, val: '', text: 'Code grants for viability (Are we eligible)', nestedLevels: 1 },
            { id: 8, val: '', text: 'Identify important dates', nestedLevels: 1 },
            { id: 9, val: '', text: 'Select a grant(s)', nestedLevels: 1 },
            { id: 10, val: '', text: 'Writing', nestedLevels: 0 },
            { id: 11, val: '', text: 'Review grant', nestedLevels: 1 },
            { id: 12, val: '', text: 'Create research questions', nestedLevels: 1 },
            { id: 13, val: '', text: 'Construct a review of literature (follow steps above)', nestedLevels: 1 },
            { id: 14, val: '', text: 'Construct narratives for sections within grant', nestedLevels: 1 },
            { id: 15, val: '', text: 'Submission', nestedLevels: 0 },
            { id: 16, val: '', text: 'Identify and contact grant contact person', nestedLevels: 1 },
            { id: 17, val: '', text: 'Plan to submit 3-7 days before deadline', nestedLevels: 1 },
            { id: 18, val: '', text: 'Submit', nestedLevels: 1 },
            { id: 19, val: '', text: 'Reach out to contact person to make sure everything is good', nestedLevels: 1 },
        ]
    },
    {
        id: 20,
        name: 'Primary Analysis',
        description: '',
        checklist: [
            { id: 1, val: '', text: 'Conduct a systematic review of literature', nestedLevels: 0 },
            { id: 2, val: '', text: 'See systematic review of literature section', nestedLevels: 1 },
            { id: 3, val: '', text: 'Identify audience for the research', nestedLevels: 0 },
            { id: 4, val: '', text: 'Determine a need for the research', nestedLevels: 0 },
            { id: 5, val: '', text: 'Secure funding', nestedLevels: 0 },
            { id: 6, val: '', text: 'See write grant section', nestedLevels: 1 },
            { id: 7, val: '', text: 'Collect data', nestedLevels: 0 },
            { id: 8, val: '', text: 'Identify sample', nestedLevels: 1 },
            { id: 9, val: '', text: 'Identify measures', nestedLevels: 1 },
            { id: 10, val: '', text: 'Identify or create instruments', nestedLevels: 1 },
            { id: 11, val: '', text: 'Review or validate instruments', nestedLevels: 1 },
            { id: 12, val: '', text: 'Archive data', nestedLevels: 0 },
            { id: 13, val: '', text: 'Identify method to archive', nestedLevels: 1 },
            { id: 14, val: '', text: 'Code data', nestedLevels: 1 },
            { id: 15, val: '', text: 'Build dictionary', nestedLevels: 1 },
            { id: 16, val: '', text: 'Conduct analysis', nestedLevels: 0 },
            { id: 17, val: '', text: 'Reporting out', nestedLevels: 1 },
            { id: 18, val: '', text: 'Send to journal for publication', nestedLevels: 2 },
            { id: 19, val: '', text: 'Use to inform future research', nestedLevels: 2 },
            { id: 20, val: '', text: 'Use as a talking note for future conferences', nestedLevels: 2 },
            { id: 21, val: '', text: 'Use to inform future grants, projects, and research', nestedLevels: 2 },
            { id: 22, val: '', text: 'Use to go into a dissertation', nestedLevels: 2 },
            { id: 23, val: '', text: 'Add to CV', nestedLevels: 2 },
        ]
    },
    {
        id: 21,
        name: 'Secondary Analysis',
        description: '',
        checklist: [
            { id: 1, val: '', text: 'Conduct a systematic review of literature', nestedLevels: 0 },
            { id: 2, val: '', text: 'See systematic review of literature section', nestedLevels: 1 },
            { id: 3, val: '', text: 'Identify audience for the research', nestedLevels: 0 },
            { id: 4, val: '', text: 'Determine a need for the research', nestedLevels: 0 },
            { id: 5, val: '', text: 'Secure funding', nestedLevels: 0 },
            { id: 6, val: '', text: 'See write grant section', nestedLevels: 1 },
            { id: 7, val: '', text: 'Collect extant data', nestedLevels: 0 },
            { id: 8, val: '', text: 'Identify or create new measures', nestedLevels: 1 },
            { id: 9, val: '', text: 'Review or validate measures', nestedLevels: 1 },
            { id: 10, val: '', text: 'Archive data', nestedLevels: 0 },
            { id: 11, val: '', text: 'Identify method to archive', nestedLevels: 1 },
            { id: 12, val: '', text: 'Code data', nestedLevels: 1 },
            { id: 13, val: '', text: 'Build dictionary', nestedLevels: 1 },
            { id: 14, val: '', text: 'Conduct analysis', nestedLevels: 0 },
            { id: 15, val: '', text: 'Reporting out', nestedLevels: 1 },
            { id: 16, val: '', text: 'Send to journal for publication', nestedLevels: 2 },
            { id: 17, val: '', text: 'Use to inform future research', nestedLevels: 2 },
            { id: 18, val: '', text: 'Use as a talking note for future conferences', nestedLevels: 2 },
            { id: 19, val: '', text: 'Use to inform future grants, projects, and research', nestedLevels: 2 },
            { id: 20, val: '', text: 'Use to go into a dissertation', nestedLevels: 2 },
            { id: 21, val: '', text: 'Add to CV', nestedLevels: 2 },
        ]
    },
    {
        id: 22,
        name: 'Meta Analysis',
        description: '',
        checklist: [
            { id: 1, val: '', text: 'Conduct a systematic review of literature', nestedLevels: 0 },
            { id: 2, val: '', text: 'See systematic review of literature section', nestedLevels: 1 },
            { id: 3, val: '', text: 'Identify audience for the research', nestedLevels: 0 },
            { id: 4, val: '', text: 'Determine a need for the research', nestedLevels: 0 },
            { id: 5, val: '', text: 'Secure funding', nestedLevels: 0 },
            { id: 6, val: '', text: 'See write grant section', nestedLevels: 1 },
            { id: 7, val: '', text: 'Collect extant sets of data', nestedLevels: 0 },
            { id: 8, val: '', text: 'Assess publication bias', nestedLevels: 1 },
            { id: 9, val: '', text: 'Identify or create new measures', nestedLevels: 1 },
            { id: 10, val: '', text: 'Review or validate measures', nestedLevels: 1 },
            { id: 11, val: '', text: 'Archive data', nestedLevels: 0 },
            { id: 12, val: '', text: 'Identify method to archive', nestedLevels: 1 },
            { id: 13, val: '', text: 'Code data', nestedLevels: 1 },
            { id: 14, val: '', text: 'Build dictionary', nestedLevels: 1 },
            { id: 15, val: '', text: 'Conduct analysis', nestedLevels: 0 },
            { id: 16, val: '', text: 'Reporting out', nestedLevels: 1 },
            { id: 17, val: '', text: 'Send to journal for publication', nestedLevels: 2 },
            { id: 18, val: '', text: 'Use to inform future research', nestedLevels: 2 },
            { id: 19, val: '', text: 'Use as a talking note for future conferences', nestedLevels: 2 },
            { id: 20, val: '', text: 'Use to inform future grants, projects, and research', nestedLevels: 2 },
            { id: 21, val: '', text: 'Use to go into a dissertation', nestedLevels: 2 },
            { id: 22, val: '', text: 'Add to CV', nestedLevels: 2 },
        ]
    },
    {
        id: 23,
        name: 'Instrument Development',
        description: '',
        checklist: [
            { id: 1, val: '', text: 'Define research objectives', nestedLevels: 0 },
            { id: 2, val: '', text: 'Identify constructs to measure', nestedLevels: 1 },
            { id: 3, val: '', text: 'Fabricate instrument items', nestedLevels: 1 },
            { id: 4, val: '', text: 'Review items with experts', nestedLevels: 1 },
            { id: 5, val: '', text: 'Choose mode of collection', nestedLevels: 0 },
            { id: 6, val: '', text: 'Identify sample', nestedLevels: 1 },
            { id: 7, val: '', text: 'Determine method of selection', nestedLevels: 1 },
            { id: 8, val: '', text: 'Determine time frame', nestedLevels: 1 },
            { id: 9, val: '', text: 'Construct and pretest instrument', nestedLevels: 0 },
            { id: 10, val: '', text: 'Create technical schematics', nestedLevels: 1 },
            { id: 11, val: '', text: 'Determine response metric', nestedLevels: 1 },
            { id: 12, val: '', text: 'Prepare beta test', nestedLevels: 1 },
            { id: 13, val: '', text: 'Beta Test', nestedLevels: 0 },
            { id: 14, val: '', text: 'Implement instrument with beta sample', nestedLevels: 1 },
            { id: 15, val: '', text: 'Collect and archive data', nestedLevels: 1 },
            { id: 16, val: '', text: 'Conduct initial analysis', nestedLevels: 1 },
            { id: 17, val: '', text: 'Revise instrument', nestedLevels: 1 },
        ]
    },
    {
        id: 24,
        name: 'Descriptive Table',
        description: '',
        checklist: [
            { id: 1, val: '', text: 'Decide on Univariate or multivariate', nestedLevels: 0 },
            { id: 2, val: '', text: 'Univariate', nestedLevels: 1 },
            { id: 3, val: '', text: 'Determine level of variable', nestedLevels: 2 },
            { id: 4, val: '', text: 'Categorical', nestedLevels: 3 },
            { id: 5, val: '', text: 'Determine mode', nestedLevels: 4 },
            { id: 6, val: '', text: 'Determine frequency', nestedLevels: 4 },
            { id: 7, val: '', text: 'Continuous', nestedLevels: 3 },
            { id: 8, val: '', text: 'Determine center (i.e. mean), spread (i.e. sd), and shape (i.e. kurtosis/skewness)', nestedLevels: 4 },
            { id: 9, val: '', text: 'Define distribution', nestedLevels: 4 },
            { id: 10, val: '', text: 'Multivariate', nestedLevels: 1 },
            { id: 11, val: '', text: 'All categorical', nestedLevels: 2 },
            { id: 12, val: '', text: 'Description or Hypothesis Test', nestedLevels: 3 },
            { id: 13, val: '', text: 'Description', nestedLevels: 4 },
            { id: 14, val: '', text: 'Determine mode for all variables', nestedLevels: 5 },
            { id: 15, val: '', text: 'Determine frequency for all variables', nestedLevels: 5 },
            { id: 16, val: '', text: 'Hypothesis Test', nestedLevels: 4 },
            { id: 17, val: '', text: 'Identify frequencies', nestedLevels: 5 },
            { id: 18, val: '', text: 'Identify percentages', nestedLevels: 5 },
            { id: 19, val: '', text: 'Identify test statistic', nestedLevels: 5 },
            { id: 20, val: '', text: 'All continuous', nestedLevels: 2 },
            { id: 21, val: '', text: 'Description or Hypothesis Test', nestedLevels: 3 },
            { id: 22, val: '', text: 'Description', nestedLevels: 4 },
            { id: 23, val: '', text: 'Determine center, spread, and shape for all variables', nestedLevels: 5 },
            { id: 24, val: '', text: 'Define distribution for all variables', nestedLevels: 5 },
            { id: 25, val: '', text: 'Hypothesis Test', nestedLevels: 4 },
            { id: 26, val: '', text: 'Identify frequencies', nestedLevels: 5 },
            { id: 27, val: '', text: 'Identify percentages', nestedLevels: 5 },
            { id: 28, val: '', text: 'Identify test statistic', nestedLevels: 5 },
            { id: 29, val: '', text: 'Categorical & Continuous (Combination)', nestedLevels: 2 },
            { id: 30, val: '', text: 'Description or Hypothesis Test', nestedLevels: 3 },
            { id: 31, val: '', text: 'Description', nestedLevels: 4 },
            { id: 32, val: '', text: 'Determine mode or center, spread, and shape for all variables', nestedLevels: 5 },
            { id: 33, val: '', text: 'Determine frequency or Define distribution for all variables', nestedLevels: 5 },
            { id: 34, val: '', text: 'Hypothesis Test', nestedLevels: 4 },
            { id: 35, val: '', text: 'Identify frequencies', nestedLevels: 5 },
            { id: 36, val: '', text: 'Identify percentages', nestedLevels: 5 },
            { id: 37, val: '', text: 'Identify test statistic', nestedLevels: 5 },
            { id: 38, val: '', text: 'Create table', nestedLevels: 0 },
        ]
    },
    {
        id: 25,
        name: 'Associative Table',
        description: '',
        checklist: [
            { id: 1, val: '', text: 'Determine level of variable', nestedLevels: 0 },
            { id: 2, val: '', text: 'Categorical', nestedLevels: 1 },
            { id: 3, val: '', text: 'Determine mode for all variables', nestedLevels: 2 },
            { id: 4, val: '', text: 'Determine frequency for all variables', nestedLevels: 2 },
            { id: 5, val: '', text: 'Continuous', nestedLevels: 1 },
            { id: 6, val: '', text: 'Determine center (i.e. mean), spread (i.e. sd), and shape (i.e. kurtosis/skewness)', nestedLevels: 2 },
            { id: 7, val: '', text: 'Define distribution', nestedLevels: 2 },
            { id: 8, val: '', text: 'Create table', nestedLevels: 0 },
        ]
    },
    {
        id: 26,
        name: 'Inferential Table',
        description: '',
        checklist: [
            { id: 1, val: '', text: 'Define empirical model', nestedLevels: 0 },
            { id: 2, val: '', text: 'Identify exemplar table in the literature', nestedLevels: 0 },
            { id: 3, val: '', text: 'Conduct analysis of the empirical model', nestedLevels: 0 },
            { id: 4, val: '', text: 'Create table', nestedLevels: 0 },
        ]
    },
    {
        id: 27,
        name: 'Conceptual Model',
        description: '',
        checklist: [
            { id: 1, val: '', text: 'Identify concepts (These things should be talked about together)', nestedLevels: 0 },
            { id: 2, val: '', text: 'Find potential variables to measure concepts', nestedLevels: 0 },
            { id: 3, val: '', text: 'Generate model', nestedLevels: 0 },
        ]
    },
    {
        id: 28,
        name: 'Theoretical Model',
        description: '',
        checklist: [
            { id: 1, val: '', text: 'Identify theories (This leads to this, or is directly related in some wya)', nestedLevels: 0 },
            { id: 2, val: '', text: 'Determine the connections between concepts', nestedLevels: 0 },
            { id: 3, val: '', text: 'Generate model', nestedLevels: 0 },
        ]
    },
    {
        id: 29,
        name: 'Empirical Model',
        description: '',
        checklist: [
            { id: 1, val: '', text: 'Create conceptual model', nestedLevels: 0 },
            { id: 2, val: '', text: 'Create theoretical model', nestedLevels: 0 },
            { id: 3, val: '', text: 'Create empirical model using math', nestedLevels: 0 },
        ]
    }
]