import Head from 'next/head';
import { Container } from '../../styles/globalPage.styles';
import Layout from '../../layouts/Layout';

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div>
          <h1>Welcome to Quester</h1>
        </div>
      </div>
    </Container>
  );
}

Home.getLayout = function getLayout(page: any) {
  return <Layout>{page}</Layout>;
};
