import { useState, useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import MainNavBar from "../components/MainNavBar";
import styled from "styled-components";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainContainer>
        <MainNavBar />
        {/* <ThemeSelector setSelectedTheme={setSelectedTheme} /> */}
        <div>
          <h1 className={styles.title}>Welcome to Quester</h1>
        </div>
      </MainContainer>
    </div>
  );
};

const MainContainer = styled.main`
  display: flex;
  min-height: 100vh;
  flex: 1;
`;

export default Home;
