import Head from 'next/head';
import styles from '../styles/Home.module.css';
import ThemeSelector from '../components/ThemeSelector/ThemeSelector';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <ThemeSelector />
        <div>
          <h1 className={styles.title}>Welcome to Quester</h1>
        </div>
      </div>
    </div>
  );
}
